In [13]:
import pandas as pd
import yfinance as yf
import plotly.offline as pyo
import numpy as np

pyo.init_notebook_mode(connected=True)
pd.options.plotting.backend = 'plotly'

In [19]:
df = yf.download(['RELIANCE.NS', 'TCS.NS', 'ONGC.NS'], start='2020-01-01', end='2025-12-31')['Close']
df

[*********************100%***********************]  3 of 3 completed

Ticker         ONGC.NS  RELIANCE.NS       TCS.NS
Date
2020-01-01   87.380310   675.324158  1866.113892
2020-01-02   87.791672   686.821167  1857.547974
2020-01-03   88.065910   687.648865  1894.567383
2020-01-06   86.557594   671.700684  1894.394287
2020-01-07   86.214790   682.034546  1899.043701
...                ...          ...          ...
2025-12-23  235.490005  1570.699951  3250.902100
2025-12-24  233.770004  1558.199951  3259.741455
2025-12-26  234.529999  1559.199951  3221.437744
2025-12-29  234.820007  1545.599976  3193.446533
2025-12-30  234.679993  1539.800049  3188.830566

[1486 rows x 3 columns]

In [23]:
log_returns = np.log(df/df.shift(1)).dropna()
log_returns

Ticker       ONGC.NS  RELIANCE.NS    TCS.NS
Date
2020-01-02  0.004697     0.016881 -0.004601
2020-01-03  0.003119     0.001204  0.019733
2020-01-06 -0.017275    -0.023466 -0.000091
2020-01-07 -0.003968     0.015267  0.002451
2020-01-08 -0.018460    -0.007538  0.022148
...              ...          ...       ...
2025-12-23  0.005578    -0.002988 -0.004491
2025-12-24 -0.007331    -0.007990  0.002715
2025-12-26  0.003246     0.000642 -0.011820
2025-12-29  0.001236    -0.008761 -0.008727
2025-12-30 -0.000596    -0.003760 -0.001446

[1485 rows x 3 columns]

In [27]:
log_returns.std()

Ticker
ONGC.NS        0.023037
RELIANCE.NS    0.017775
TCS.NS         0.014965
dtype: float64

In [31]:
Position = df.iloc[-1]
Position

Ticker
ONGC.NS         234.679993
RELIANCE.NS    1539.800049
TCS.NS         3188.830566
Name: 2025-12-30 00:00:00, dtype: float64

In [99]:
from scipy.stats import norm

# This is for quantity

In [109]:
shares = pd.Series({
    'ONGC.NS': 100,
    'RELIANCE.NS': 50,
    'TCS.NS': 10
})

position = shares * df.iloc[-1]        
sigma = log_returns.std()
z = abs(norm.ppf(0.95))

VaR_array = position * sigma * z
VaR_array

ONGC.NS         889.275364
RELIANCE.NS    2251.022214
TCS.NS          784.952115
dtype: float64

# This is for equaly capital allocation

In [113]:
capital_per_stock = 100_000  # ₹1 lakh each

position_value = pd.Series(
    capital_per_stock,
    index=log_returns.columns
)

VaR_array2 = position_value * sigma * z
VaR_array2

Ticker
ONGC.NS        3789.310515
RELIANCE.NS    2923.785093
TCS.NS         2461.567332
dtype: float64